### ISSUE TITLE
Crypt problem

### ISSUE THREAD

**Issue by vpervenditti** [wison27/sg-patch-tools#1]
How to encrypt a translated file?

**Comment by wison27** [comment]
The scripts was encrypted using the xor-like crypt. Thus the encrypt and decrypt are the same algorithm.

USAGE: ./sgcrypt.py ANDROID_FILE [NEW_FILE] [OPTIONS]

OPTIONS:
        -s, --script            Force process as script file
        -n, --not-script      Force process as not script file
        -h, --help             This help page

**Comment by wison27** [comment]
@vpervenditti the -n is for encrypt/decrypt images/videos and others assets of sg android (that do not are script files)
